version: "3.8"

services:
  culta_backend_fa:
    container_name: culta_backend_fa
    image: culta_backend_fa
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REAL_DATABASE_URL: "postgresql+asyncpg://nikita:12345@172.17.0.1:5432/main_db"
    ports:
      - "8000:8000"
    restart: unless-stopped
