from image.interface_response.create_image_response import CreateImageResponse, CreateImageInterface
from image.interface_response.get_image_response import GetImageInterface, GetImageResponse
from image.interface_response.delete_image_response import DeleteImageResponse
from image.interface_response.update_image_response import UpdateImageResponse
from image.interface_response.get_images_in_company_response import GetImagesInCompanyResponse



