"""test migr 6

Revision ID: 006c9b8fb211
Revises: 368f69351a2d
Create Date: 2024-10-18 17:11:00.518725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '006c9b8fb211'
down_revision = '368f69351a2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_card', 'company_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'product_card', 'company', ['company_id'], ['company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_card', type_='foreignkey')
    op.alter_column('product_card', 'company_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
