"""change fileds name in image db_model 2

Revision ID: 0cbbc9e07074
Revises: 2325106c2893
Create Date: 2025-02-11 14:30:57.318038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cbbc9e07074'
down_revision = '2325106c2893'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('is_used', sa.Boolean(), nullable=True))
    op.drop_column('image', 'is_archived')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('image', 'is_used')
    # ### end Alembic commands ###
