"""change fileds name in image db_model

Revision ID: 16290a9faa30
Revises: e78bff6e1970
Create Date: 2025-02-07 11:05:11.220225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16290a9faa30'
down_revision = 'e78bff6e1970'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('file_path', sa.String(length=1000), nullable=True))
    op.drop_column('image', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('image', 'file_path')
    # ### end Alembic commands ###
