"""fix bugs fields screen

Revision ID: 19344920ebfe
Revises: e0d6aba44de0
Create Date: 2024-10-26 00:46:58.518636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19344920ebfe'
down_revision = 'e0d6aba44de0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
