"""update model company import

Revision ID: 1dc716a5a5b5
Revises: d4a37a385fc9
Create Date: 2024-10-17 20:14:39.477279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc716a5a5b5'
down_revision = 'd4a37a385fc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
