"""add model screen

Revision ID: 1e8a628a72f3
Revises: cf26b2fff64e
Create Date: 2024-10-26 00:07:13.148139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e8a628a72f3'
down_revision = 'cf26b2fff64e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screen',
    sa.Column('screen_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('screen_title', sa.String(length=100), nullable=True),
    sa.Column('screen_sub_title', sa.String(length=100), nullable=True),
    sa.Column('screen_count_number', sa.Integer(), nullable=True),
    sa.Column('company_group_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('updater_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('screen_id')
    )
    op.add_column('container', sa.Column('screen_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'container', 'screen', ['screen_id'], ['screen_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'container', type_='foreignkey')
    op.drop_column('container', 'screen_id')
    op.drop_table('screen')
    # ### end Alembic commands ###
