"""add model item

Revision ID: 24444a19620c
Revises: b7f734e1f172
Create Date: 2024-10-23 19:13:58.002144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24444a19620c'
down_revision = 'b7f734e1f172'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('item_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('item_row_order', sa.Integer(), nullable=True),
    sa.Column('item_column_order', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=35), nullable=True),
    sa.Column('product_card_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['product_card_id'], ['product_card.product_card_id'], ),
    sa.PrimaryKeyConstraint('item_id', 'product_card_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
