"""drop field images in company

Revision ID: 2f9908dcb884
Revises: 0cbbc9e07074
Create Date: 2025-02-13 11:08:18.931121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9908dcb884'
down_revision = '0cbbc9e07074'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
