"""test migr 7

Revision ID: 30e83020ebd7
Revises: 006c9b8fb211
Create Date: 2024-10-18 17:20:16.830146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e83020ebd7'
down_revision = '006c9b8fb211'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_card', sa.Column('title', sa.String(length=35), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_card', 'title')
    # ### end Alembic commands ###
