"""test migr 5

Revision ID: 368f69351a2d
Revises: d9b0bc8afbca
Create Date: 2024-10-18 17:05:56.723749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368f69351a2d'
down_revision = 'd9b0bc8afbca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_card_company_id_fkey', 'product_card', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('product_card_company_id_fkey', 'product_card', 'company', ['company_id'], ['company_id'])
    # ### end Alembic commands ###
