"""add field basic_screen_id in company model

Revision ID: 3d28cd8e4004
Revises: 19344920ebfe
Create Date: 2024-10-27 20:19:31.142427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d28cd8e4004'
down_revision = '19344920ebfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('basic_screen_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_column('company', 'main_screen_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('main_screen_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('company', 'basic_screen_id')
    # ### end Alembic commands ###
