"""refactoring  image model

Revision ID: 4f31c2a35b87
Revises: ca7b9edaf77e
Create Date: 2025-03-10 17:08:56.181606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f31c2a35b87'
down_revision = 'ca7b9edaf77e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
