"""fix field company_id in user_role model

Revision ID: 500e77aed5b6
Revises: 3531a30450f6
Create Date: 2024-12-21 08:43:54.133053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '500e77aed5b6'
down_revision = '3531a30450f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_role', 'company_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_role', 'company_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
