"""test migr 2

Revision ID: 895ca76f7f21
Revises: 974c6eb7e358
Create Date: 2024-10-18 16:06:49.174444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895ca76f7f21'
down_revision = '974c6eb7e358'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_card', 'description')
    op.drop_column('product_card', 'product_quantity')
    op.drop_column('product_card', 'price_field_2')
    op.drop_column('product_card', 'quantity_system')
    op.drop_column('product_card', 'title')
    op.drop_column('product_card', 'single_product_type')
    op.drop_column('product_card', 'price_field_1')
    op.drop_column('product_card', 'bonuses_payment')
    op.drop_column('product_card', 'sub_title')
    op.drop_column('product_card', 'is_hotness')
    op.drop_column('product_card', 'product_category')
    op.drop_column('product_card', 'count_number')
    op.drop_column('product_card', 'product_release_type')
    op.drop_column('product_card', 'product_image_id')
    op.drop_column('product_card', 'cashback_field_1')
    op.drop_column('product_card', 'proteins')
    op.drop_column('product_card', 'allergens_list')
    op.drop_column('product_card', 'cost_price_field_1')
    op.drop_column('product_card', 'fats')
    op.drop_column('product_card', 'calorie_content')
    op.drop_column('product_card', 'icon_image_id')
    op.drop_column('product_card', 'hint_header')
    op.drop_column('product_card', 'tags')
    op.drop_column('product_card', 'company_group_id')
    op.drop_column('product_card', 'custom_product_category')
    op.drop_column('product_card', 'header')
    op.drop_column('product_card', 'cashback_field_2')
    op.drop_column('product_card', 'is_sharpness')
    op.drop_column('product_card', 'hint_description')
    op.drop_column('product_card', 'cost_price_field_2')
    op.drop_column('product_card', 'carbohydrates')
    op.drop_column('product_card', 'cooking_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_card', sa.Column('cooking_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('carbohydrates', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('cost_price_field_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('hint_description', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('is_sharpness', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('cashback_field_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('header', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('custom_product_category', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('company_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('tags', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('hint_header', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('icon_image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('calorie_content', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('fats', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('cost_price_field_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('allergens_list', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('proteins', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('cashback_field_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('product_image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('product_release_type', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('count_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('product_category', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('is_hotness', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('sub_title', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('bonuses_payment', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('price_field_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('single_product_type', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('title', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('quantity_system', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('price_field_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('product_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('description', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
