"""test migr 1

Revision ID: 974c6eb7e358
Revises: 3b862fcd5988
Create Date: 2024-10-18 16:03:27.325884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '974c6eb7e358'
down_revision = '3b862fcd5988'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_card', 'updater_id')
    op.drop_column('product_card', 'creator_id')
    op.drop_column('product_card', 'time_updated')
    op.drop_column('product_card', 'time_created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_card', sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('time_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('creator_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('updater_id', postgresql.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
