"""add avatar_id for user_role_db

Revision ID: aa73234e9c62
Revises: b0f1396b1a54
Create Date: 2025-11-09 15:26:26.626980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa73234e9c62'
down_revision = 'b0f1396b1a54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column('avatar_id', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_role', 'avatar_id')
    # ### end Alembic commands ###
