"""fix filed types product_card

Revision ID: ace24e72ae9f
Revises: 66bf6dc366bd
Create Date: 2024-10-22 12:56:12.961967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace24e72ae9f'
down_revision = '66bf6dc366bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
