"""refactoring model  AuthModel

Revision ID: b0f1396b1a54
Revises: b94334306b2f
Create Date: 2025-08-24 00:13:17.152579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0f1396b1a54'
down_revision = 'b94334306b2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_accounts',
    sa.Column('auth_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', 'YANDEX', 'TELEGRAM', 'APPLE', name='authprovider'), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('auth_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_accounts')
    # ### end Alembic commands ###
