"""add flag is_active product_card

Revision ID: b7f734e1f172
Revises: ace24e72ae9f
Create Date: 2024-10-22 14:16:06.735101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f734e1f172'
down_revision = 'ace24e72ae9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_card', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_card', 'is_active')
    # ### end Alembic commands ###
