"""add oAuthModel

Revision ID: b94334306b2f
Revises: 4f31c2a35b87
Create Date: 2025-08-19 22:58:21.781808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b94334306b2f'
down_revision = '4f31c2a35b87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
