"""fix field container_order

Revision ID: bab353f34589
Revises: 500e77aed5b6
Create Date: 2025-02-01 12:44:56.963544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab353f34589'
down_revision = '500e77aed5b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('container', 'container_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'container', ['container_order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'container', type_='unique')
    op.alter_column('container', 'container_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
