"""add model image with relationship

Revision ID: c037e5efd8fd
Revises: 3d28cd8e4004
Create Date: 2024-10-31 17:32:57.590916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c037e5efd8fd'
down_revision = '3d28cd8e4004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('image_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('type_col', sa.String(length=100), nullable=True),
    sa.Column('image_type', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('resolution', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.String(length=100), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('company_group_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('image_id', 'company_id')
    )
    op.add_column('company', sa.Column('image_picture_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('company', sa.Column('image_icon_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_column('company', 'company_icon')
    op.drop_column('company', 'company_image')
    op.add_column('product_card', sa.Column('image_product_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('product_card', sa.Column('image_icon_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_column('product_card', 'product_image_id')
    op.drop_column('product_card', 'icon_image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_card', sa.Column('icon_image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_card', sa.Column('product_image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('product_card', 'image_icon_id')
    op.drop_column('product_card', 'image_product_id')
    op.add_column('company', sa.Column('company_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('company_icon', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('company', 'image_icon_id')
    op.drop_column('company', 'image_picture_id')
    op.drop_table('image')
    # ### end Alembic commands ###
