"""return field title in image model

Revision ID: ca7b9edaf77e
Revises: 2f9908dcb884
Create Date: 2025-02-27 23:34:53.579094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7b9edaf77e'
down_revision = '2f9908dcb884'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'title')
    # ### end Alembic commands ###
