"""fix bugs container

Revision ID: cf26b2fff64e
Revises: 6093996c6648
Create Date: 2024-10-25 23:35:17.544258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf26b2fff64e'
down_revision = '6093996c6648'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
