"""update model company

Revision ID: d4a37a385fc9
Revises: 5a66b1cb7fbf
Create Date: 2024-10-17 20:05:54.130446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a37a385fc9'
down_revision = '5a66b1cb7fbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
