"""test migr 4

Revision ID: d9b0bc8afbca
Revises: 895ca76f7f21
Create Date: 2024-10-18 16:53:55.785921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b0bc8afbca'
down_revision = '895ca76f7f21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
