"""add foriegn key in screen

Revision ID: e0d6aba44de0
Revises: 1e8a628a72f3
Create Date: 2024-10-26 00:07:46.812482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0d6aba44de0'
down_revision = '1e8a628a72f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screen', sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'screen', 'company', ['company_id'], ['company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'screen', type_='foreignkey')
    op.drop_column('screen', 'company_id')
    # ### end Alembic commands ###
