"""fix field screen_order_number and conteiner_order_number

Revision ID: e78bff6e1970
Revises: 71ba95b6d216
Create Date: 2025-02-01 13:50:45.396156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78bff6e1970'
down_revision = '71ba95b6d216'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('container_container_order_number_key', 'container', type_='unique')
    op.alter_column('screen', 'screen_sub_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint('screen_screen_order_number_key', 'screen', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('screen_screen_order_number_key', 'screen', ['screen_order_number'])
    op.alter_column('screen', 'screen_sub_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint('container_container_order_number_key', 'container', ['container_order_number'])
    # ### end Alembic commands ###
