"""add relationship for model item

Revision ID: ee6f61b63e02
Revises: 24444a19620c
Create Date: 2024-10-24 14:35:39.859669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee6f61b63e02'
down_revision = '24444a19620c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
