"""add relationship screen with company

Revision ID: f2d8afb7289f
Revises: c037e5efd8fd
Create Date: 2024-10-31 19:17:00.192043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d8afb7289f'
down_revision = 'c037e5efd8fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
