import uuid
from enum import Enum

EMPTY_UUID = uuid.UUID(int=0)


class PortalRole(str, Enum):
    PORTAL_ROLE_USER = 'PORTAL_ROLE_USER'
    PORTAL_ROLE_STAFF = 'PORTAL_ROLE_STAFF'
    PORTAL_ROLE_ADMIN = 'PORTAL_ROLE_ADMIN'
    PORTAL_ROLE_SUPER_ADMIN = 'PORTAL_ROLE_SUPER_ADMIN'
